services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    # Remove ports mapping - let Coolify handle this
    expose:
      - "80"
    environment:
      TZ: 'America/Toronto'
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
