services:
     wallos:
       container_name: wallos
       image: bellamy/wallos:latest
       ports:
         - "80:80"  # Standard HTTP port
       environment:
         TZ: 'America/Toronto'
       volumes:
         - './db:/var/www/html/db'
         - './logos:/var/www/html/images/uploads/logos'
       restart: unless-stopped
